---
- hosts: "{{ host }}"
  # remote_user: "{{ remoteuser }}"
  vars:
    target_major_version: "{{ ansible_facts['distribution_major_version'] }}"
    target_family: "{{ ansible_facts['os_family']|lower }}"
    target: "{{ target_family }}{{ target_major_version }}"

   
  tasks:

    - import_role:
        name: hub-base
      vars:
        nrts_src_version: ""  # currently unused, but should in ufutre, pull from github "release" version
        system_hostname: idahub7
        nrts_home_dir : "{{ nrts_home }}"
        nrts_user_auth: "{{ nrts_auth }}"
        git_src_branch: "{{ git_src_branch }}"

