# os_family == 'debian' SYSTEM SPECIFIC

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true

- name: install system pkgs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  become: true
  loop: 
    - openssh-client
    - openssh-server
    - make
    - zlib1g-dev
    - wget
    - gcc
    - ncurses-base
    - libxml2-dev
    - libuser
    - csh
    - tcsh
    - vim
    - ntp
    - cron
    - git
    - lsof
    - man-db 
    - manpages-posix
    - octave
    - octave-doc
    - octave-info
    - octave-htmldoc
    - liboctave-dev
    # - epel-release
    # - iftop
    # - xorriso
    # - tree
    # # - ncurses-bin
    # xorriso really only for centos 7.7+, but need to get rid of ISOs all together.